//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meds_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meds_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Med.
        /// </summary>
        public static string Add_eng {
            get {
                return ResourceManager.GetString("Add_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă medicament.
        /// </summary>
        public static string Add_ro {
            get {
                return ResourceManager.GetString("Add_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new med.
        /// </summary>
        public static string AddANewMed_eng {
            get {
                return ResourceManager.GetString("AddANewMed_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă un medicament nou.
        /// </summary>
        public static string AddANewMed_ro {
            get {
                return ResourceManager.GetString("AddANewMed_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add picture.
        /// </summary>
        public static string AddPicture_eng {
            get {
                return ResourceManager.GetString("AddPicture_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă poză.
        /// </summary>
        public static string AddPicture_ro {
            get {
                return ResourceManager.GetString("AddPicture_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds App.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base substance:.
        /// </summary>
        public static string BaseSubstance_eng {
            get {
                return ResourceManager.GetString("BaseSubstance_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substanță de bază:.
        /// </summary>
        public static string BaseSubstance_ro {
            get {
                return ResourceManager.GetString("BaseSubstance_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base substance quantity:.
        /// </summary>
        public static string BaseSubstanceQuantity_eng {
            get {
                return ResourceManager.GetString("BaseSubstanceQuantity_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate substanță de bază:.
        /// </summary>
        public static string BaseSubstanceQuantity_ro {
            get {
                return ResourceManager.GetString("BaseSubstanceQuantity_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best before:.
        /// </summary>
        public static string BestBefore_eng {
            get {
                return ResourceManager.GetString("BestBefore_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exipirării:.
        /// </summary>
        public static string BestBefore_ro {
            get {
                return ResourceManager.GetString("BestBefore_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_eng {
            get {
                return ResourceManager.GetString("Delete_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge.
        /// </summary>
        public static string Delete_ro {
            get {
                return ResourceManager.GetString("Delete_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description_eng {
            get {
                return ResourceManager.GetString("Description_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere:.
        /// </summary>
        public static string Description_ro {
            get {
                return ResourceManager.GetString("Description_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_eng {
            get {
                return ResourceManager.GetString("Details_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii.
        /// </summary>
        public static string Details_ro {
            get {
                return ResourceManager.GetString("Details_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search for a med by name, description or base substance!.
        /// </summary>
        public static string HelpSearch_eng {
            get {
                return ResourceManager.GetString("HelpSearch_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puteți să căutați un medicament după nume, descriere sau substanța de bază!.
        /// </summary>
        public static string HelpSearch_ro {
            get {
                return ResourceManager.GetString("HelpSearch_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_eng {
            get {
                return ResourceManager.GetString("Home_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acasă.
        /// </summary>
        public static string Home_ro {
            get {
                return ResourceManager.GetString("Home_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Arrow {
            get {
                object obj = ResourceManager.GetObject("LOGO-Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Exit {
            get {
                object obj = ResourceManager.GetObject("LOGO_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Flag_Ro {
            get {
                object obj = ResourceManager.GetObject("LOGO-Flag-Ro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Flag_Uk_Small {
            get {
                object obj = ResourceManager.GetObject("Logo_Flag_Uk_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Help {
            get {
                object obj = ResourceManager.GetObject("LOGO-Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Home {
            get {
                object obj = ResourceManager.GetObject("LOGO-Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_List {
            get {
                object obj = ResourceManager.GetObject("LOGO-List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Med {
            get {
                object obj = ResourceManager.GetObject("LOGO-Med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_OutOfDate {
            get {
                object obj = ResourceManager.GetObject("LOGO-OutOfDate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Settings {
            get {
                object obj = ResourceManager.GetObject("LOGO-Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_eng {
            get {
                return ResourceManager.GetString("Name_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume:.
        /// </summary>
        public static string Name_ro {
            get {
                return ResourceManager.GetString("Name_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of date.
        /// </summary>
        public static string OutOfDate_eng {
            get {
                return ResourceManager.GetString("OutOfDate_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expirat.
        /// </summary>
        public static string OutOfDate_ro {
            get {
                return ResourceManager.GetString("OutOfDate_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces:.
        /// </summary>
        public static string Pieces_eng {
            get {
                return ResourceManager.GetString("Pieces_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucăți:.
        /// </summary>
        public static string Pieces_ro {
            get {
                return ResourceManager.GetString("Pieces_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_eng {
            get {
                return ResourceManager.GetString("Save_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvează.
        /// </summary>
        public static string Save_ro {
            get {
                return ResourceManager.GetString("Save_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_eng {
            get {
                return ResourceManager.GetString("Search_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caută.
        /// </summary>
        public static string Search_ro {
            get {
                return ResourceManager.GetString("Search_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for managing home medicines.
        /// </summary>
        public static string Title_eng {
            get {
                return ResourceManager.GetString("Title_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicație pentru gestionarea medicamentelor personale.
        /// </summary>
        public static string Title_ro {
            get {
                return ResourceManager.GetString("Title_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type_eng {
            get {
                return ResourceManager.GetString("Type_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        public static string Type_ro {
            get {
                return ResourceManager.GetString("Type_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_eng {
            get {
                return ResourceManager.GetString("Update_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizează.
        /// </summary>
        public static string Update_ro {
            get {
                return ResourceManager.GetString("Update_ro", resourceCulture);
            }
        }
    }
}
