//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meds_App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meds_App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Med.
        /// </summary>
        public static string Add_eng {
            get {
                return ResourceManager.GetString("Add_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă medicament.
        /// </summary>
        public static string Add_ro {
            get {
                return ResourceManager.GetString("Add_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new medicine.
        /// </summary>
        public static string AddANewMed_eng {
            get {
                return ResourceManager.GetString("AddANewMed_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă un medicament nou.
        /// </summary>
        public static string AddANewMed_ro {
            get {
                return ResourceManager.GetString("AddANewMed_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add picture.
        /// </summary>
        public static string AddPicture_eng {
            get {
                return ResourceManager.GetString("AddPicture_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă poză.
        /// </summary>
        public static string AddPicture_ro {
            get {
                return ResourceManager.GetString("AddPicture_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds App.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base substance:.
        /// </summary>
        public static string BaseSubstance_eng {
            get {
                return ResourceManager.GetString("BaseSubstance_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substanță de bază:.
        /// </summary>
        public static string BaseSubstance_ro {
            get {
                return ResourceManager.GetString("BaseSubstance_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base substance quantity:.
        /// </summary>
        public static string BaseSubstanceQuantity_eng {
            get {
                return ResourceManager.GetString("BaseSubstanceQuantity_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitate substanță de bază:.
        /// </summary>
        public static string BaseSubstanceQuantity_ro {
            get {
                return ResourceManager.GetString("BaseSubstanceQuantity_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best before:.
        /// </summary>
        public static string BestBefore_eng {
            get {
                return ResourceManager.GetString("BestBefore_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exipirării:.
        /// </summary>
        public static string BestBefore_ro {
            get {
                return ResourceManager.GetString("BestBefore_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright_eng {
            get {
                return ResourceManager.GetString("Copyright_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drepturi de autor.
        /// </summary>
        public static string Copyright_ro {
            get {
                return ResourceManager.GetString("Copyright_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © PNGGuru.
        /// </summary>
        public static string CopyrightFlag {
            get {
                return ResourceManager.GetString("CopyrightFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Github.
        /// </summary>
        public static string CopyrightGithub {
            get {
                return ResourceManager.GetString("CopyrightGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Timothy Miller Free icon.
        /// </summary>
        public static string CopyrightHome {
            get {
                return ResourceManager.GetString("CopyrightHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_eng {
            get {
                return ResourceManager.GetString("Delete_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge.
        /// </summary>
        public static string Delete_ro {
            get {
                return ResourceManager.GetString("Delete_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description_eng {
            get {
                return ResourceManager.GetString("Description_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere:.
        /// </summary>
        public static string Description_ro {
            get {
                return ResourceManager.GetString("Description_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_eng {
            get {
                return ResourceManager.GetString("Details_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii.
        /// </summary>
        public static string Details_ro {
            get {
                return ResourceManager.GetString("Details_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details about medicine.
        /// </summary>
        public static string DetailsAbout_eng {
            get {
                return ResourceManager.GetString("DetailsAbout_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalii despre medicament.
        /// </summary>
        public static string DetailsAbout_ro {
            get {
                return ResourceManager.GetString("DetailsAbout_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email*:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reportbugpassword2020.
        /// </summary>
        public static string Email_password {
            get {
                return ResourceManager.GetString("Email_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reportmedicinebug@gmail.com.
        /// </summary>
        public static string Email_user {
            get {
                return ResourceManager.GetString("Email_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_eng {
            get {
                return ResourceManager.GetString("Error_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eroare.
        /// </summary>
        public static string Error_ro {
            get {
                return ResourceManager.GetString("Error_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base substance!.
        /// </summary>
        public static string ErrorBaseSubst_eng {
            get {
                return ResourceManager.GetString("ErrorBaseSubst_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substanță de bază invalidă!.
        /// </summary>
        public static string ErrorBaseSubst_ro {
            get {
                return ResourceManager.GetString("ErrorBaseSubst_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be a positive number of base substance quantity!.
        /// </summary>
        public static string ErrorBaseSubstQ1_eng {
            get {
                return ResourceManager.GetString("ErrorBaseSubstQ1_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitatea substanței de bază trebuie să fie un număr pozitiv!.
        /// </summary>
        public static string ErrorBaseSubstQ1_ro {
            get {
                return ResourceManager.GetString("ErrorBaseSubstQ1_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No base substance quanitity measure selected!.
        /// </summary>
        public static string ErrorBaseSubstQ2_eng {
            get {
                return ResourceManager.GetString("ErrorBaseSubstQ2_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați selectat gramajul substanței be bază!.
        /// </summary>
        public static string ErrorBaseSubstQ2_ro {
            get {
                return ResourceManager.GetString("ErrorBaseSubstQ2_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid description!.
        /// </summary>
        public static string ErrorDescription_eng {
            get {
                return ResourceManager.GetString("ErrorDescription_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere invalidă!.
        /// </summary>
        public static string ErrorDescription_ro {
            get {
                return ResourceManager.GetString("ErrorDescription_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid or is empty!.
        /// </summary>
        public static string ErrorEmail_eng {
            get {
                return ResourceManager.GetString("ErrorEmail_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa de email invalidă!.
        /// </summary>
        public static string ErrorEmail_ro {
            get {
                return ResourceManager.GetString("ErrorEmail_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no problem description!.
        /// </summary>
        public static string ErrorMessage_eng {
            get {
                return ResourceManager.GetString("ErrorMessage_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați completat descrierea problemei!.
        /// </summary>
        public static string ErrorMessage_ro {
            get {
                return ResourceManager.GetString("ErrorMessage_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name!.
        /// </summary>
        public static string ErrorName_eng {
            get {
                return ResourceManager.GetString("ErrorName_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume invalid!.
        /// </summary>
        public static string ErrorName_ro {
            get {
                return ResourceManager.GetString("ErrorName_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be a positive number of pieces!.
        /// </summary>
        public static string ErrorPieces_eng {
            get {
                return ResourceManager.GetString("ErrorPieces_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantitatea medicamentului trebuie să fie un număr pozitiv!.
        /// </summary>
        public static string ErrorPieces_ro {
            get {
                return ResourceManager.GetString("ErrorPieces_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds cound not be retrived from server.
        /// </summary>
        public static string ErrorRetrieve_eng {
            get {
                return ResourceManager.GetString("ErrorRetrieve_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicamentele nu au putut fi preluate de pe server.
        /// </summary>
        public static string ErrorRetrieve_ro {
            get {
                return ResourceManager.GetString("ErrorRetrieve_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type selected!.
        /// </summary>
        public static string ErrorType_eng {
            get {
                return ResourceManager.GetString("ErrorType_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ați selectat un tip!.
        /// </summary>
        public static string ErrorType_ro {
            get {
                return ResourceManager.GetString("ErrorType_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to add! Please try again!.
        /// </summary>
        public static string FailedToAdd_eng {
            get {
                return ResourceManager.GetString("FailedToAdd_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu a fost adăugat! Vă rog să mai încercați!.
        /// </summary>
        public static string FailedToAdd_ro {
            get {
                return ResourceManager.GetString("FailedToAdd_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to delete! Please try again!.
        /// </summary>
        public static string FailedToDelete_eng {
            get {
                return ResourceManager.GetString("FailedToDelete_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu a fost șters! Vă rog să mai încercați!.
        /// </summary>
        public static string FailedToDelete_ro {
            get {
                return ResourceManager.GetString("FailedToDelete_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug was not reported! Please try again!.
        /// </summary>
        public static string FailedToSend_eng {
            get {
                return ResourceManager.GetString("FailedToSend_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema nu a fost raportată! Vă rog să mai încercați!.
        /// </summary>
        public static string FailedToSend_ro {
            get {
                return ResourceManager.GetString("FailedToSend_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to update! Please try again!.
        /// </summary>
        public static string FailedToUpdate_eng {
            get {
                return ResourceManager.GetString("FailedToUpdate_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu a fost actualizat! Vă rog să mai încercați!.
        /// </summary>
        public static string FailedToUpdate_ro {
            get {
                return ResourceManager.GetString("FailedToUpdate_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GitHub_Mark_120px_plus {
            get {
                object obj = ResourceManager.GetObject("GitHub-Mark-120px-plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GitHub_Mark_64px {
            get {
                object obj = ResourceManager.GetObject("GitHub-Mark-64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clear and concise description of the issue.
        ///Describe what happened and what you expected to happen.
        ///Steps to reproduce the issue, if available.
        ///Screenshots of the issue, if relevant.
        ///Any error messages you received..
        /// </summary>
        public static string HelpReport_eng {
            get {
                return ResourceManager.GetString("HelpReport_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O descriere clară și concisă a problemei. 
        ///Descrieți ce s-a întâmplat și ce v-ați așteptatat să se întâmple.
        ///Pașii pentru a reproduce problema, dacă îi m-ai știți.
        ///Capturi de ecran ale problemei, dacă credeți că este relevant.
        ///Orice mesaj de eroare ați primit..
        /// </summary>
        public static string HelpReport_ro {
            get {
                return ResourceManager.GetString("HelpReport_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should I include in my bug report?.
        /// </summary>
        public static string HelpReportTitle_eng {
            get {
                return ResourceManager.GetString("HelpReportTitle_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce ar trebui să includ în raportul meu de erori?.
        /// </summary>
        public static string HelpReportTitle_ro {
            get {
                return ResourceManager.GetString("HelpReportTitle_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search for a med by name, description or base substance!.
        /// </summary>
        public static string HelpSearch_eng {
            get {
                return ResourceManager.GetString("HelpSearch_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puteți să căutați un medicament după nume, descriere sau substanța de bază!.
        /// </summary>
        public static string HelpSearch_ro {
            get {
                return ResourceManager.GetString("HelpSearch_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for something?.
        /// </summary>
        public static string HelpSearchTitle_eng {
            get {
                return ResourceManager.GetString("HelpSearchTitle_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Căutați ceva?.
        /// </summary>
        public static string HelpSearchTitle_ro {
            get {
                return ResourceManager.GetString("HelpSearchTitle_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_eng {
            get {
                return ResourceManager.GetString("Home_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acasă.
        /// </summary>
        public static string Home_ro {
            get {
                return ResourceManager.GetString("Home_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files(*.jpg;*.png)|*.jpg;*.png|All files(*.*)|*.*.
        /// </summary>
        public static string ImageFiles_eng {
            get {
                return ResourceManager.GetString("ImageFiles_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fișiere imagine(*.jpg;*.png)|*.jpg;*.png|Toate fișierele(*.*)|*.*.
        /// </summary>
        public static string ImageFiles_ro {
            get {
                return ResourceManager.GetString("ImageFiles_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Arrow {
            get {
                object obj = ResourceManager.GetObject("LOGO-Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Arrow_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_Arrow_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Exit {
            get {
                object obj = ResourceManager.GetObject("LOGO_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Exit_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_Exit_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Flag_Ro {
            get {
                object obj = ResourceManager.GetObject("LOGO-Flag-Ro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Flag_Uk_Small {
            get {
                object obj = ResourceManager.GetObject("Logo_Flag_Uk_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Help {
            get {
                object obj = ResourceManager.GetObject("LOGO-Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Help_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_Help_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Home {
            get {
                object obj = ResourceManager.GetObject("LOGO-Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Home_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_Home_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_List {
            get {
                object obj = ResourceManager.GetObject("LOGO-List", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_List_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_List_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Med {
            get {
                object obj = ResourceManager.GetObject("LOGO-Med", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Med_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_Med_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Med_white2 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Med_white2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_OutOfDate {
            get {
                object obj = ResourceManager.GetObject("LOGO-OutOfDate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_OutOfDate_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_OutOfDate_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Refresh {
            get {
                object obj = ResourceManager.GetObject("LOGO-Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Refresh_White {
            get {
                object obj = ResourceManager.GetObject("LOGO_Refresh_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LOGO_Settings {
            get {
                object obj = ResourceManager.GetObject("LOGO-Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Theme_Dark_small {
            get {
                object obj = ResourceManager.GetObject("Logo-Theme-Dark_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo_Theme_White_small {
            get {
                object obj = ResourceManager.GetObject("Logo-Theme-White_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med added.
        /// </summary>
        public static string MedAdded_eng {
            get {
                return ResourceManager.GetString("MedAdded_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicament adăugat.
        /// </summary>
        public static string MedAdded_ro {
            get {
                return ResourceManager.GetString("MedAdded_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_eng {
            get {
                return ResourceManager.GetString("Name_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume:.
        /// </summary>
        public static string Name_ro {
            get {
                return ResourceManager.GetString("Name_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to echo off
        ///cls
        ///echo Server will open soon...
        ///cd &quot;C:\Users\colde\source\repos\ColdCipri\Meds-Server\Meds-Server&quot;
        ///dotnet run --urls http://*:5050.
        /// </summary>
        public static string openServer {
            get {
                return ResourceManager.GetString("openServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of date.
        /// </summary>
        public static string OutOfDate_eng {
            get {
                return ResourceManager.GetString("OutOfDate_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expirat.
        /// </summary>
        public static string OutOfDate_ro {
            get {
                return ResourceManager.GetString("OutOfDate_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  medicines are out of date! Do you want to see them?.
        /// </summary>
        public static string OutOfDateCount_eng {
            get {
                return ResourceManager.GetString("OutOfDateCount_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  medicamente expirate! Doriți să vedeți care sunt acestea?.
        /// </summary>
        public static string OutOfDateCount_ro {
            get {
                return ResourceManager.GetString("OutOfDateCount_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A medicine is out of date! Do you want to see it?.
        /// </summary>
        public static string OutOfDateCount1_eng {
            get {
                return ResourceManager.GetString("OutOfDateCount1_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un medicament a expirat! Doriți să vedeți care e acesta?.
        /// </summary>
        public static string OutOfDateCount1_ro {
            get {
                return ResourceManager.GetString("OutOfDateCount1_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This medicine is out of date from .
        /// </summary>
        public static string OutOfDateDetails_eng {
            get {
                return ResourceManager.GetString("OutOfDateDetails_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acest medicament a expirat în .
        /// </summary>
        public static string OutOfDateDetails_ro {
            get {
                return ResourceManager.GetString("OutOfDateDetails_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pieces:.
        /// </summary>
        public static string Pieces_eng {
            get {
                return ResourceManager.GetString("Pieces_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucăți:.
        /// </summary>
        public static string Pieces_ro {
            get {
                return ResourceManager.GetString("Pieces_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem description*:.
        /// </summary>
        public static string ProblemDescription_eng {
            get {
                return ResourceManager.GetString("ProblemDescription_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrierea problemei*:.
        /// </summary>
        public static string ProblemDescription_ro {
            get {
                return ResourceManager.GetString("ProblemDescription_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string Report_eng {
            get {
                return ResourceManager.GetString("Report_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raportează o problemă.
        /// </summary>
        public static string Report_ro {
            get {
                return ResourceManager.GetString("Report_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_eng {
            get {
                return ResourceManager.GetString("Save_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvează.
        /// </summary>
        public static string Save_ro {
            get {
                return ResourceManager.GetString("Save_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_eng {
            get {
                return ResourceManager.GetString("Search_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caută.
        /// </summary>
        public static string Search_ro {
            get {
                return ResourceManager.GetString("Search_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send_eng {
            get {
                return ResourceManager.GetString("Send_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimite.
        /// </summary>
        public static string Send_ro {
            get {
                return ResourceManager.GetString("Send_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code for the application is available on github..
        /// </summary>
        public static string SourceCodeApp_eng {
            get {
                return ResourceManager.GetString("SourceCodeApp_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codul sursă al aplicației este disponibil pe github..
        /// </summary>
        public static string SourceCodeApp_ro {
            get {
                return ResourceManager.GetString("SourceCodeApp_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code for the server is available on github..
        /// </summary>
        public static string SourceCodeServer_eng {
            get {
                return ResourceManager.GetString("SourceCodeServer_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codul sursă al serverului este disponibil pe github..
        /// </summary>
        public static string SourceCodeServer_ro {
            get {
                return ResourceManager.GetString("SourceCodeServer_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success_eng {
            get {
                return ResourceManager.GetString("Success_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes.
        /// </summary>
        public static string Success_ro {
            get {
                return ResourceManager.GetString("Success_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully added!.
        /// </summary>
        public static string SuccessfullyAdded_eng {
            get {
                return ResourceManager.GetString("SuccessfullyAdded_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adăugat cu succes!.
        /// </summary>
        public static string SuccessfullyAdded_ro {
            get {
                return ResourceManager.GetString("SuccessfullyAdded_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully deleted!.
        /// </summary>
        public static string SuccessfullyDeleted_eng {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a fost șters cu succes!.
        /// </summary>
        public static string SuccessfullyDeleted_ro {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report sent! Thank you for your feedback!.
        /// </summary>
        public static string SuccessfullySend_eng {
            get {
                return ResourceManager.GetString("SuccessfullySend_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema a fost raportată! Mulțumim pentru feedback-ul tău!.
        /// </summary>
        public static string SuccessfullySend_ro {
            get {
                return ResourceManager.GetString("SuccessfullySend_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully updated!.
        /// </summary>
        public static string SuccessfullyUpdated_eng {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actualizat cu succes!.
        /// </summary>
        public static string SuccessfullyUpdated_ro {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for managing home medicines.
        /// </summary>
        public static string Title_eng {
            get {
                return ResourceManager.GetString("Title_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug!.
        /// </summary>
        public static string Title_Report_eng {
            get {
                return ResourceManager.GetString("Title_Report_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raportează o eroare!.
        /// </summary>
        public static string Title_Report_ro {
            get {
                return ResourceManager.GetString("Title_Report_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicație pentru gestionarea medicamentelor personale.
        /// </summary>
        public static string Title_ro {
            get {
                return ResourceManager.GetString("Title_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type_eng {
            get {
                return ResourceManager.GetString("Type_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        public static string Type_ro {
            get {
                return ResourceManager.GetString("Type_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cream.
        /// </summary>
        public static string TypeCream_eng {
            get {
                return ResourceManager.GetString("TypeCream_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cremă.
        /// </summary>
        public static string TypeCream_ro {
            get {
                return ResourceManager.GetString("TypeCream_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drops.
        /// </summary>
        public static string TypeDrops_eng {
            get {
                return ResourceManager.GetString("TypeDrops_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picături.
        /// </summary>
        public static string TypeDrops_ro {
            get {
                return ResourceManager.GetString("TypeDrops_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effervescent.
        /// </summary>
        public static string TypeEffervescent_eng {
            get {
                return ResourceManager.GetString("TypeEffervescent_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efervescent.
        /// </summary>
        public static string TypeEffervescent_ro {
            get {
                return ResourceManager.GetString("TypeEffervescent_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gel.
        /// </summary>
        public static string TypeGel {
            get {
                return ResourceManager.GetString("TypeGel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pill.
        /// </summary>
        public static string TypePill_eng {
            get {
                return ResourceManager.GetString("TypePill_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastilă.
        /// </summary>
        public static string TypePill_ro {
            get {
                return ResourceManager.GetString("TypePill_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spray.
        /// </summary>
        public static string TypeSpray {
            get {
                return ResourceManager.GetString("TypeSpray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppository.
        /// </summary>
        public static string TypeSuppository_eng {
            get {
                return ResourceManager.GetString("TypeSuppository_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supozitor.
        /// </summary>
        public static string TypeSuppository_ro {
            get {
                return ResourceManager.GetString("TypeSuppository_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syrup.
        /// </summary>
        public static string TypeSyrup_eng {
            get {
                return ResourceManager.GetString("TypeSyrup_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirop.
        /// </summary>
        public static string TypeSyrup_ro {
            get {
                return ResourceManager.GetString("TypeSyrup_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tea.
        /// </summary>
        public static string TypeTea_eng {
            get {
                return ResourceManager.GetString("TypeTea_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceai.
        /// </summary>
        public static string TypeTea_ro {
            get {
                return ResourceManager.GetString("TypeTea_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_eng {
            get {
                return ResourceManager.GetString("Update_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizează.
        /// </summary>
        public static string Update_ro {
            get {
                return ResourceManager.GetString("Update_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning_eng {
            get {
                return ResourceManager.GetString("Warning_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atentie.
        /// </summary>
        public static string Warning_ro {
            get {
                return ResourceManager.GetString("Warning_ro", resourceCulture);
            }
        }
    }
}
